POST http://localhost:8080/customers
Content-Type: application/json

{
  "FirstName": "Przemysław 3 ",
  "LastName": "Kijak 3 ",
  "Email": "przemyslaw@kijak.com",
  "DateOfBirth": "1992-01-01"
}

###
