services:
  outputcaching:
    image: outputcaching
    build:
      context: ./
      dockerfile: ./OutputCaching/Dockerfile
    ports:
      - 8080:8080
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./DatabaseScripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - "6379:6379"
volumes:
  postgres_data: