services:
  cqrs-api:
    image: cqrs-api
    build:
      context: ./
      dockerfile: ./CQRSApi/Dockerfile
    ports:
      - 8080:8080
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data_cqrs:/var/lib/postgresql/data
      - ./DatabaseScripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  postgres_data_cqrs: